kind: ConfigMap
apiVersion: v1
metadata:
  name: uptime-kuma-flb-sc-config-map
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2024-01-30T21:48:34Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:fluent-bit.conf': {}
          'f:parsers.conf': {}
        'f:immutable': {}
immutable: false
data:
  fluent-bit.conf: |-
    [SERVICE]
       Flush        1
       Daemon       Off
       Log_Level    debug
       HTTP_Server   On
       HTTP_Listen   0.0.0.0
       HTTP_Port     2020
       Parsers_File parsers.conf
    [INPUT]
       Name   tail
       Path   /mnt/log/*.log
       Exclude_Path *.gz,*.zip
       Parser docker
       Mem_Buf_Limit 20MB
       db monitored_file_offset.db
    [FILTER]
       Name record_modifier
       Match *
       Record hostname ${HOSTNAME}
    [OUTPUT]
       Name   stdout
       Format json_lines
       Match  *
    [OUTPUT]
       Name  splunk
       Match *
       Host  hec.monitoring.ag.gov.bc.ca
       Port  8088
       TLS         On
       TLS.Verify  Off
       Message_Key uptime-kuma
       Splunk_Token 35bb57d6-b9be-4ea8-8546-861dc064d2ac
  parsers.conf: |-
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S-%z
