kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cron-log-storage-backup
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: netapp-file-standard
  volumeMode: Filesystem

